--Condition
--Create a query to separate duplicated data.

WITH SRC AS (
    SELECT '1000 1100' CO, '841000 841100' IDC FROM DUAL
    UNION ALL
    SELECT '2000', '6700 8967 5500' FROM DUAL
),
RNUMB AS (
    SELECT ROWNUM RN, CO, IDC
    FROM SRC
)
SELECT (CASE CNT WHEN 0 THEN TO_CHAR(RN) ELSE ' ' END) RN, CNT, 
       NVL((CASE CNT WHEN 0 THEN CO ELSE NCO END), ' ') CODE_OPERATION,
       NVL((CASE CNT WHEN 0 THEN IDC ELSE NIDC END), ' ') ID_CLIENT
FROM RNUMB
MODEL
PARTITION BY (RN)
DIMENSION BY (CAST (0 AS NUMBER(5)) AS CNT)
MEASURES (CO, IDC, CAST ('' AS VARCHAR2(30)) AS NCO, CAST ('' AS VARCHAR2(30)) AS NIDC)
RULES ITERATE(100) UNTIL (ITERATION_NUMBER + 1 >= NVL(REGEXP_COUNT(CO[0], '[^ ]+'), 0) AND
                          ITERATION_NUMBER + 1 >= NVL(REGEXP_COUNT(IDC[0], '[^ ]+'), 0)) (
    NCO[ITERATION_NUMBER + 1] = REGEXP_SUBSTR(CO[0], '[^ ]+', 1, ITERATION_NUMBER + 1),  
    NIDC[ITERATION_NUMBER + 1] = REGEXP_SUBSTR(IDC[0], '[^ ]+', 1, ITERATION_NUMBER + 1)
);
