--Condition
--Display information about schema tables in the form: Table name, Primary key columns, 
--Columns with uniqueness constraints, List of subordinate tables with secondary key columns.

WITH PK AS (
    SELECT DISTINCT T.TABLE_NAME, NVL(LISTAGG(CC.COLUMN_NAME, ', ') WITHIN
           GROUP (ORDER BY CC.POSITION) OVER (PARTITION BY CP.CONSTRAINT_NAME), ' ') COLS
    FROM USER_TABLES T
    JOIN USER_CONS_COLUMNS CC ON (T.TABLE_NAME = CC.TABLE_NAME)
    JOIN USER_CONSTRAINTS CP ON (CP.CONSTRAINT_NAME = CC.CONSTRAINT_NAME)
    WHERE CP.CONSTRAINT_TYPE = 'P'
),
FK AS (
    SELECT DISTINCT CR.TABLE_NAME MAIN, CC.TABLE_NAME,
           NVL(LISTAGG(CC.COLUMN_NAME, ', ') WITHIN GROUP (ORDER BY CC.POSITION) OVER
           (PARTITION BY C.CONSTRAINT_NAME),' ') COLS
    FROM USER_CONS_COLUMNS CC
    JOIN USER_CONSTRAINTS C ON (CC.CONSTRAINT_NAME = C.CONSTRAINT_NAME)
    JOIN USER_CONSTRAINTS CR ON (C.R_CONSTRAINT_NAME = CR.CONSTRAINT_NAME)
    WHERE C.CONSTRAINT_TYPE = 'R'
),
UK AS (
    SELECT DISTINCT T.TABLE_NAME, LISTAGG(CC.COLUMN_NAME, ', ') WITHIN GROUP
           (ORDER BY CC.POSITION) OVER (PARTITION BY CP.CONSTRAINT_NAME) COLS
    FROM USER_TABLES T
    JOIN USER_CONS_COLUMNS CC ON (T.TABLE_NAME = CC.TABLE_NAME)
    JOIN USER_CONSTRAINTS CP ON (CP.CONSTRAINT_NAME = CC.CONSTRAINT_NAME)
    WHERE CP.CONSTRAINT_TYPE = 'U'
)
SELECT DISTINCT ALL_T.TABLE_NAME "??? ???????", NVL(PK.COLS,'-') "??????? ??",
       NVL(UK.COLS,'-') "??????? ??????????? ?????", 
       LISTAGG(NVL2(FK.COLS, FK.TABLE_NAME || '(' || FK.COLS || ')', '-'),', ') 
       WITHIN GROUP (ORDER BY FK.TABLE_NAME) OVER (PARTITION BY ALL_T.TABLE_NAME, UK.COLS) "??????? FK ??????????? ??????"
FROM USER_TABLES ALL_T
LEFT OUTER JOIN UK ON (ALL_T.TABLE_NAME = UK.TABLE_NAME)
LEFT OUTER JOIN FK ON (ALL_T.TABLE_NAME = FK.MAIN)
LEFT OUTER JOIN PK ON (ALL_T.TABLE_NAME = PK.TABLE_NAME)
ORDER BY 1;
