--Condition
--Using a data dictionary, obtain information about restrictions
--CHECK schemes:
--In lists, column names are separated by commas. The table name should not repeat.
--Solve the problem without using the Listagg and Wm_concat functions.

WITH SRC AS (
    SELECT UC.TABLE_NAME TABN, UC.CONSTRAINT_NAME CONN, 
           UCC.COLUMN_NAME COLN, UC.SEARCH_CONDITION_VC TXT
    FROM USER_CONSTRAINTS UC
    JOIN USER_CONS_COLUMNS UCC ON (UC.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME)
    WHERE UC.CONSTRAINT_TYPE = 'C'
),
RNUMB AS (
    SELECT ROW_NUMBER() OVER (PARTITION BY TABN ORDER BY CONN, COLN) TR,
           DENSE_RANK() OVER (ORDER BY TABN, CONN) CR,
           ROW_NUMBER() OVER (PARTITION BY CONN ORDER BY COLN) RN,
           COUNT(*) OVER (PARTITION BY CONN) CNT,
           TABN, CONN, COLN, TXT
    FROM SRC
),
MODI AS (
    SELECT TR, TABN, CONN, COLN, TXT
    FROM RNUMB
    MODEL
    RETURN UPDATED ROWS
    PARTITION BY (CR)
    DIMENSION BY (RN)
    MEASURES (TR, CNT, TABN, CONN, COLN, TXT)
    RULES ITERATE (10) UNTIL (ITERATION_NUMBER + 1 >= CNT[1]) (
        COLN[1] = (CASE ITERATION_NUMBER WHEN 0 THEN COLN[1] ELSE COLN[1] || ',' || COLN[ITERATION_NUMBER + 1] END)
    )
) 
SELECT (CASE TR WHEN 1 THEN TABN ELSE ' ' END) TABLE_NAME,
       CONN CONSTRAINT_NAME, COLN COLUMNS, TXT TEXT
FROM MODI
ORDER BY TABN, TR;
